name: Build Windows Executable

on:
  push:
    tags:
      - 'v*'  # Run on versioned tags (e.g., v1.0, v2.1)
  workflow_dispatch:  # Allow manual triggering

permissions:
  packages: write

jobs:
  build:
    runs-on: windows-latest  # ✅ Change to Windows environment

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.3'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -r requirements.txt

      - name: Build Windows Executable
        run: |
          pyinstaller --onefile ExtractCMCsFromPDF.py

      - name: Upload artifact (Windows EXE)
        uses: actions/upload-artifact@v4  # ✅ Updated for latest version
        with:
          name: ExtractCMCsFromPDF.exe
          path: dist/ExtractCMCsFromPDF.exe  # ✅ Windows executable

      - name: Create Release and Upload Executable
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: dist/ExtractCMCsFromPDF.exe  # ✅ Windows EXE release
