name: Build and Test Windows Executable

on:
  push:
    tags:
      - 'v*'  # Run on versioned tags (e.g., v1.0, v2.1)
  pull_request:  # Run tests on PRs
  workflow_dispatch:  # Allow manual triggering

permissions:
  contents: write

jobs:
  test:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.3'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tests
        run: |
          $env:PYTHONPATH = "$env:GITHUB_WORKSPACE"
          pytest tests/ --maxfail=1 --disable-warnings -q

  build:
    needs: test
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.3'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build Windows Executable
        run: |
          pyinstaller CMCs_PdfToCsv.exe.spec

      - name: Upload artifact (Windows EXE)
        uses: actions/upload-artifact@v4
        with:
          name: CMCs_PdfToCsv.exe
          path: dist/CMCs_PdfToCsv.exe

      - name: Create Release and Upload Executable
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: dist/CMCs_PdfToCsv.exe
          generate_release_notes: true
